/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Praktikum4;

/**
 *
 * @author User
 */
public class Kalkulator_perbandingan extends javax.swing.JFrame {
    
    int nilai_a,nilai_b;
    boolean hasil;
    /**
     * Creates new form Kalkulator_perbandingan
     */
    public Kalkulator_perbandingan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtpertama = new javax.swing.JTextField();
        txtkedua = new javax.swing.JTextField();
        btntidaksama = new javax.swing.JButton();
        btnsama = new javax.swing.JButton();
        btnlebih = new javax.swing.JButton();
        btnkurang = new javax.swing.JButton();
        btnlbhsama = new javax.swing.JButton();
        btnkurangsama = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txthasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PROGRAM OPERATOR PEMBANDING");

        jLabel2.setText("NILAI A");

        jLabel3.setText("NILAI B");

        btntidaksama.setText("!=");
        btntidaksama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntidaksamaActionPerformed(evt);
            }
        });

        btnsama.setText("==");
        btnsama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsamaActionPerformed(evt);
            }
        });

        btnlebih.setText(">");
        btnlebih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlebihActionPerformed(evt);
            }
        });

        btnkurang.setText("<");
        btnkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkurangActionPerformed(evt);
            }
        });

        btnlbhsama.setText(">=");
        btnlbhsama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlbhsamaActionPerformed(evt);
            }
        });

        btnkurangsama.setText("<=");
        btnkurangsama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkurangsamaActionPerformed(evt);
            }
        });

        jLabel4.setText("HASIL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtkedua, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtpertama, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnsama)
                                .addGap(18, 18, 18)
                                .addComponent(btntidaksama)
                                .addGap(18, 18, 18)
                                .addComponent(btnlebih)
                                .addGap(18, 18, 18)
                                .addComponent(btnkurang)
                                .addGap(18, 18, 18)
                                .addComponent(btnlbhsama))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txthasil, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnkurangsama)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtpertama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtkedua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntidaksama)
                    .addComponent(btnsama)
                    .addComponent(btnlebih)
                    .addComponent(btnkurang)
                    .addComponent(btnlbhsama)
                    .addComponent(btnkurangsama))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txthasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntidaksamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntidaksamaActionPerformed
        // TODO add your handling code here:
        nilai_a = Integer.valueOf(txtpertama.getText());
        nilai_b = Integer.valueOf(txtkedua.getText());
        
        hasil = (nilai_a != nilai_b);
        
        txthasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_btntidaksamaActionPerformed

    private void btnsamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsamaActionPerformed
        // TODO add your handling code here:
        nilai_a = Integer.valueOf(txtpertama.getText());
        nilai_b = Integer.valueOf(txtkedua.getText());
        
        hasil = (nilai_a == nilai_b);
        
        txthasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_btnsamaActionPerformed

    private void btnlebihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlebihActionPerformed
        // TODO add your handling code here:
        nilai_a = Integer.valueOf(txtpertama.getText());
        nilai_b = Integer.valueOf(txtkedua.getText());
        
        hasil = (nilai_a > nilai_b);
        
        txthasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_btnlebihActionPerformed

    private void btnkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkurangActionPerformed
        // TODO add your handling code here:
        nilai_a = Integer.valueOf(txtpertama.getText());
        nilai_b = Integer.valueOf(txtkedua.getText());
        
        hasil = (nilai_a < nilai_b);
        
        txthasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_btnkurangActionPerformed

    private void btnlbhsamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlbhsamaActionPerformed
        // TODO add your handling code here:
        nilai_a = Integer.valueOf(txtpertama.getText());
        nilai_b = Integer.valueOf(txtkedua.getText());
        
        hasil = (nilai_a >= nilai_b);
        
        txthasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_btnlbhsamaActionPerformed

    private void btnkurangsamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkurangsamaActionPerformed
        // TODO add your handling code here:
        nilai_a = Integer.valueOf(txtpertama.getText());
        nilai_b = Integer.valueOf(txtkedua.getText());
        
        hasil = (nilai_a <= nilai_b);
        
        txthasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_btnkurangsamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator_perbandingan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator_perbandingan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator_perbandingan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator_perbandingan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator_perbandingan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnkurang;
    private javax.swing.JButton btnkurangsama;
    private javax.swing.JButton btnlbhsama;
    private javax.swing.JButton btnlebih;
    private javax.swing.JButton btnlebihsama;
    private javax.swing.JButton btnlebihsama1;
    private javax.swing.JButton btnlebihsama2;
    private javax.swing.JButton btnlebihsama3;
    private javax.swing.JButton btnsama;
    private javax.swing.JButton btntidaksama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txthasil;
    private javax.swing.JTextField txtkedua;
    private javax.swing.JTextField txtpertama;
    // End of variables declaration//GEN-END:variables
}
